# Generated by Django 4.1.3 on 2023-05-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
